version: "3.9"
services:
  api:
    build: .
    container_name: express_api
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - .:/app:cached
      - /app/node_modules
    command: node app.js
    depends_on:
      - mysql
    networks:
      - mynetwork

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
